# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
markdown: redcarpet
redcarpet:
  extensions: ["strikethrough", "with_toc_data"]
title:               Matt Trifilo
tagline:             'JavaScript is eating the world.'
description:         "JavaScript developer, cyclist, keto carnivore. Let's speak in code."
url:                 https://blog.matttrifilo.com
baseurl:             ''
gems: [jekyll-paginate]
paginate:            5
paginate_path: "page:num"

# About/contact
author:
  name:              Matt Trifilo
  url:               http://www.matttrifilo.com
  email:             matt.trifilo@gmail.com
  twitter:			 https://twitter.com/matttrifilo

# Custom vars
version:             1.0.0
